/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Database {
  /**
   * Begin a write transaction. Must `.commit()` or `.rollback()`.
   * Dropping without either rolls back.
   */
  transaction(): Transaction
  /** SELECT returns `Array<Object>` (each row is a plain object). */
  query(sql: string, params?: Array<JsonValue> | undefined | null): Array<Record<string, any>>
  /**
   * Filesystem watcher on the .db-wal file. `await ev.next()` resolves
   * on every commit to the database (any process, any writer).
   */
  walEvents(): WalEvents
  /**
   * Delete notifications older than a duration, or beyond a count.
   * Returns number of rows removed.
   */
  pruneNotifications(olderThanS?: number | undefined | null, maxKeep?: number | undefined | null): number
}

export declare class Transaction {
  execute(sql: string, params?: Array<JsonValue> | undefined | null): number
  query(sql: string, params?: Array<JsonValue> | undefined | null): Array<Record<string, any>>
  /**
   * Publish a cross-process notification. `payload` should be a
   * JSON string (caller JSON-encodes); this keeps the wire shape
   * explicit and matches the Python side.
   */
  notify(channel: string, payload: string): number
  commit(): void
  rollback(): void
}

export declare class WalEvents {
  /** Await the next WAL change. Resolves on every DB commit. */
  next(): Promise<void>
  /** Stop the background stat-poll thread. */
  close(): void
}

export declare function open(path: string, maxReaders?: number | undefined | null): Database
